### PR TITLE
Copy RN stylesheet

### PR DESCRIPTION
**Pull request by timantmedia**
Restyling the docs according to https://github.com/orgs/ant-media/projects/3/views/1?filterQuery=assignee%3Atimantmedia&pane=issue&itemId=43086608

### CODE REVIEW

**Comment by asharamseervi** [comment]
Hi @timantmedia, I believe that this change will make our documentation more readable and accessible for our readers. Thank you for your work to give a refreshing look to our documentation.

**Comment by timantmedia** [comment]
@asharamseervi thank you for your feedback. I'll keep working it then to give it a more customized feel.

**Comment by mustafaboleken** [comment]
It looks good but I have a comment. Light/Dark switch button is not visible in light mode and header logo should be modified in dark mode.

Screenshot 2023-11-04 at 11 35 04
Screenshot 2023-11-04 at 11 36 13

**Comment by timantmedia** [comment]
Thanks I'll edit. I think menu is also not consistent I'll change that as well.

**Comment by timantmedia** [comment]
To many redundant styles and is messy.

**Pull request closed without merging**
