### PR TITLE
first draft of quick start

### PR DESCRIPTION
**Pull request by timantmedia**
Make the quick start guide simple and quick.

### CODE REVIEW

**Comment by asharamseervi** [comment]
It looks better now. If you are done with changes, please mark this pr for review. Thanks.

**Comment by timantmedia** [comment]
@mekya please comment on the quick start changes. Is this what you had in mind 
Preview link:  https://deploy-preview-81--ant-media-documentation.netlify.app/

**Comment by mekya** [comment]
Hi @timantmedia,
Let me give some feedforwards

- When I copy the script, it copies two lines and it does not work because there is no <ANT_MEDIA_SERVER_ZIP_FILE> 
sudo wget https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh && sudo chmod 755 install_ant-media-server.sh sudo ./install_ant-media-server.sh -i <ANT_MEDIA_SERVER_ZIP_FILE>  
- Please also mention the new installation type without giving the zip file
- Make free subdomain first
- Show some screenshots 
- Forward the user more samples and tools
- Update the images [such as this one](https://deploy-preview-81--ant-media-documentation.netlify.app/assets/images/138691164-04d3f2c7-f37a-4acd-a590-2af05477e256-ee928cb5240ed6d85af026950f63a818.png) appears here https://deploy-preview-81--ant-media-documentation.netlify.app/get-started/sample-tools-and-applications/
- Put person images there to show confidence and camera usage.

**Comment by timantmedia** [comment]
Looks like the build failed, not sure why. It builds fine on my local machine. @asharamseervi I made sure to keep the branch updated and synced.

**Comment by timantmedia** [comment]
@mekya please give feed forwards on latest preview https://deploy-preview-81--ant-media-documentation.netlify.app/quick-start/

**Comment by timantmedia** [comment]
@asharamseervi localhost removed.

**Comment by timantmedia** [comment]
@mekya please let me know if this revised quick start page is more inline.

**Comment by mekya** [comment]
What is blocking you to merge this PR? 😞  @asharamseervi

**Review by mustafaboleken — APPROVED** [review]
lgtm

**Review by mekya — APPROVED** [review]

**Pull request merged**
