### PR TITLE
some format fixed to look better

### PR DESCRIPTION
**Pull request by timantmedia**
I know we haven't planned to edit these docs, I just couldn't leave the formatting of these looking so bad. They were quick fixes to make it look more appealing.

### CODE REVIEW

**Review by asharamseervi — APPROVED** [review]
Looks good to me.

**Comment by timantmedia** [comment]
@asharamseervi I had some conflicts with the meta on each page. Do you need the title: Title or can we add a custom title?

**Comment by asharamseervi** [comment]
Hi @timantmedia, yes, it will give conflicts as this PR was in the stale mode for a while, and I had made changes to almost every file specially related title, descriptions, and keywords here: https://github.com/ant-media/ant-media-documentation/pull/57

title: Title doesn't make sense, either you may use it the one I used in mentioned PR to avoid conflicts, or you may introduce a better one, and we'll merge.

**Comment by asharamseervi** [comment]
I am merging it and fixing the title: Title in another PR to avoid further conflicts.

**Pull request merged**
