### PR TITLE
add docs to have all the TS files listed in m3u8 file

### PR DESCRIPTION
**Pull request by USAMAWIZARD**
### What does it do?

Describe your PR here.

### Why is it needed?

Describe the issue you are solving. It would be great if you reference issue here with brief description.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. In many cases, features are absent for a reason. If you don't have an issue, please create one.
- [ ] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs:`, or `refactor:`.
- [ ] The description should clearly illustrate what problems it solves.
- [ ] Ensure that the commit messages follow our guidelines.
- [ ] Resolve merge conflicts (if any).
- [ ] Make sure that the current branch is upto date with the `main` branch.

### CODE REVIEW

**Comment by USAMAWIZARD** [comment]
https://github.com/ant-media/Ant-Media-Server/issues/5529

**Review by timantmedia — CHANGES_REQUESTED** [review]
I think we can reword like this:

HLS streaming is a more cost-effective and secure method of streaming than video on-demand assets. Furthermore, you can also record the HLS stream. Simply change your application's HLS settings in the file `/usr/local/antmedia/webapps/App-Name/WEB-INF/red5-web.properties` and configure the setting below:

**Comment by Mohit-3196** [comment]
Hi @USAMAWIZARD,
Can you please incorporate the changes suggested by @timantmedia 
Let me know after you do it so that I can approve the PR.

Thank you

**Review by Mohit-3196 — APPROVED** [review]
Looks good to me.

**Pull request merged**
